PROFILE = "user"

SMONITOR = {
    "level": "WARNING",
    "trace_depth": 3,
    "capture_warnings": False,
    "capture_logging": True,
    "theme": "plain",
}

PROFILES = {
    "user": {
        "level": "WARNING",
    },
    "dev": {
        "level": "INFO",
        "show_traceback": True,
    },
    "qa": {
        "level": "INFO",
        "show_traceback": True,
    },
    "agent": {
        "level": "WARNING",
    },
    "debug": {
        "level": "DEBUG",
        "show_traceback": True,
    },
}

CODES = {
    "MOLSYSVIEWER-ARGUMENT-ERROR": {
        "title": "Invalid argument",
        "user_message": "The argument '{argument}' has an invalid value in '{caller}'.",
        "user_hint": "Review the argument requirements and try again. Docs: {doc_url}. Issues: {issues_url}.",
        "dev_message": "Invalid argument '{argument}' in '{caller}' with value '{value}'.",
        "dev_hint": "Validate inputs or update the digesters for '{caller}'.",
        "qa_message": "Invalid argument '{argument}' in '{caller}'.",
        "qa_hint": "Cover invalid inputs for '{caller}'.",
        "agent_message": "Invalid argument '{argument}' in '{caller}'.",
        "agent_hint": "Check input validation rules and update tests.",
    },
    "MOLSYSVIEWER-FILE-ALREADY-HANDLED": {
        "title": "File already handled",
        "user_message": "The file '{filename}' is already handled by MolSysViewer.",
        "user_hint": "Remove duplicates or load the file once.",
        "dev_message": "File '{filename}' already handled; duplicate load attempt.",
        "dev_hint": "Guard file registration or deduplicate inputs.",
        "qa_message": "File '{filename}' already handled; duplicate load attempt.",
        "qa_hint": "Add coverage for duplicate file handling.",
        "agent_message": "File '{filename}' already handled.",
        "agent_hint": "Avoid duplicate load attempts.",
    },
    "MOLSYSVIEWER-ITERATOR-ERROR": {
        "title": "Iterator error",
        "user_message": "There was a problem with iterator arguments in '{caller}'.",
        "user_hint": "Check the iterator inputs and try again. Docs: {doc_url}.",
        "dev_message": "Iterator arguments error in '{caller}'.",
        "dev_hint": "Validate iterator inputs and bounds.",
        "qa_message": "Iterator arguments error in '{caller}'.",
        "qa_hint": "Add coverage for iterator edge cases.",
        "agent_message": "Iterator arguments error in '{caller}'.",
        "agent_hint": "Check iterator validation logic.",
    },
    "MOLSYSVIEWER-LIBRARY-NOT-FOUND": {
        "title": "Missing optional dependency",
        "user_message": "Optional dependency '{library}' was not found.",
        "user_hint": "Install '{library}' to enable this feature. Docs: {doc_url}.",
        "dev_message": "Optional dependency '{library}' missing in '{caller}'.",
        "dev_hint": "Document optional dependency or add guard paths.",
        "qa_message": "Optional dependency '{library}' missing.",
        "qa_hint": "Validate behavior with and without '{library}'.",
        "agent_message": "Optional dependency '{library}' missing.",
        "agent_hint": "Ensure feature checks for dependency availability.",
    },
    "MOLSYSVIEWER-MOLECULAR-SYSTEM-NEEDED": {
        "title": "Molecular system required",
        "user_message": "'{caller}' requires exactly one molecular system.",
        "user_hint": "Provide a single molecular system input.",
        "dev_message": "'{caller}' requires a single molecular system.",
        "dev_hint": "Validate inputs before calling '{caller}'.",
        "qa_message": "'{caller}' requires a single molecular system.",
        "qa_hint": "Add coverage for missing or multiple systems.",
        "agent_message": "'{caller}' requires a single molecular system.",
        "agent_hint": "Verify input preparation pipeline.",
    },
    "MOLSYSVIEWER-MOLECULAR-SYSTEMS-NEEDED": {
        "title": "Multiple molecular systems required",
        "user_message": "'{caller}' requires multiple molecular systems.",
        "user_hint": "Provide two or more molecular systems as input.",
        "dev_message": "'{caller}' requires multiple molecular systems.",
        "dev_hint": "Validate input count before calling '{caller}'.",
        "qa_message": "'{caller}' requires multiple molecular systems.",
        "qa_hint": "Add coverage for insufficient system inputs.",
        "agent_message": "'{caller}' requires multiple molecular systems.",
        "agent_hint": "Check input preparation pipeline.",
    },
    "MOLSYSVIEWER-NOT-COMPATIBLE-CONVERSION": {
        "title": "Incompatible conversion",
        "user_message": "Conversion from '{from_form}' to '{to_form}' is missing required inputs.",
        "user_hint": "Provide the missing inputs and try again.",
        "dev_message": "Conversion '{from_form}' -> '{to_form}' missing {missing_arguments}.",
        "dev_hint": "Add required inputs or adjust conversion support.",
        "qa_message": "Conversion '{from_form}' -> '{to_form}' missing {missing_arguments}.",
        "qa_hint": "Test conversions with missing inputs.",
        "agent_message": "Conversion '{from_form}' -> '{to_form}' missing {missing_arguments}.",
        "agent_hint": "Update conversion preconditions.",
    },
    "MOLSYSVIEWER-NOT-IMPLEMENTED-CONVERSION": {
        "title": "Conversion not implemented",
        "user_message": "Conversion from '{from_form}' to '{to_form}' is not implemented.",
        "user_hint": "Choose a supported conversion or update MolSysViewer.",
        "dev_message": "Conversion '{from_form}' -> '{to_form}' not implemented in '{caller}'.",
        "dev_hint": "Implement conversion or add a clear fallback.",
        "qa_message": "Conversion '{from_form}' -> '{to_form}' not implemented.",
        "qa_hint": "Track coverage for unsupported conversions.",
        "agent_message": "Conversion '{from_form}' -> '{to_form}' not implemented.",
        "agent_hint": "Plan conversion support or add guards.",
    },
    "MOLSYSVIEWER-NOT-IMPLEMENTED-ITERATOR": {
        "title": "Iterator not implemented",
        "user_message": "Iterator for form '{form}' is not implemented.",
        "user_hint": "Choose a supported form or update MolSysViewer.",
        "dev_message": "Iterator for form '{form}' not implemented in '{caller}'.",
        "dev_hint": "Implement iterator or add a clear fallback.",
        "qa_message": "Iterator for form '{form}' not implemented.",
        "qa_hint": "Track unsupported iterator forms.",
        "agent_message": "Iterator for form '{form}' not implemented.",
        "agent_hint": "Plan iterator support or add guards.",
    },
    "MOLSYSVIEWER-NOT-IMPLEMENTED-METHOD": {
        "title": "Method not implemented",
        "user_message": "This method is not implemented yet.",
        "user_hint": "Update MolSysViewer or choose a supported method.",
        "dev_message": "Method not implemented in '{caller}'.",
        "dev_hint": "Implement the method or raise a clearer alternative.",
        "qa_message": "Method not implemented in '{caller}'.",
        "qa_hint": "Track coverage for unimplemented methods.",
        "agent_message": "Method not implemented in '{caller}'.",
        "agent_hint": "Plan implementation or add guards.",
    },
    "MOLSYSVIEWER-NOT-SUPPORTED-FORM": {
        "title": "Form not supported",
        "user_message": "The form '{form}' is not supported in '{caller}'.",
        "user_hint": "Use a supported form or convert your input.",
        "dev_message": "Form '{form}' not supported in '{caller}'.",
        "dev_hint": "Add support for '{form}' or improve error guidance.",
        "qa_message": "Form '{form}' not supported in '{caller}'.",
        "qa_hint": "Add coverage for unsupported forms.",
        "agent_message": "Form '{form}' not supported in '{caller}'.",
        "agent_hint": "Plan form support or add guards.",
    },
    "MOLSYSVIEWER-NOT-SUPPORTED-SYNTAX": {
        "title": "Syntax not supported",
        "user_message": "The syntax '{syntax}' is not supported in '{caller}'.",
        "user_hint": "Use a supported syntax or update MolSysViewer.",
        "dev_message": "Syntax '{syntax}' not supported in '{caller}'.",
        "dev_hint": "Add support for '{syntax}' or improve guidance.",
        "qa_message": "Syntax '{syntax}' not supported in '{caller}'.",
        "qa_hint": "Add coverage for unsupported syntax.",
        "agent_message": "Syntax '{syntax}' not supported in '{caller}'.",
        "agent_hint": "Plan syntax support or add guards.",
    },
    "MOLSYSVIEWER-NOT-WITH-THIS-FORM": {
        "title": "Incompatible form",
        "user_message": "This method cannot work with the provided form in '{caller}'.",
        "user_hint": "Use a compatible form or check the API docs.",
        "dev_message": "Incompatible form in '{caller}'.",
        "dev_hint": "Add support or clarify accepted forms.",
        "qa_message": "Incompatible form in '{caller}'.",
        "qa_hint": "Add coverage for incompatible forms.",
        "agent_message": "Incompatible form in '{caller}'.",
        "agent_hint": "Plan form support or add guards.",
    },
    "MOLSYSVIEWER-NOT-DIGESTED-ARGUMENT": {
        "title": "Argument not digested",
        "user_message": "The argument '{argument}' was not digested for '{caller}'.",
        "user_hint": "Check the argument name or update MolSysViewer.",
        "dev_message": "Argument '{argument}' not digested in '{caller}'.",
        "dev_hint": "Register a digester for '{argument}'.",
        "qa_message": "Argument '{argument}' not digested in '{caller}'.",
        "qa_hint": "Add coverage for undigested arguments.",
        "agent_message": "Argument '{argument}' not digested in '{caller}'.",
        "agent_hint": "Add a digester or update rules.",
    },
    "MOLSYSVIEWER-VIEWER-INIT-FAILED": {
        "title": "Viewer initialization failed",
        "user_message": "MolSysViewer failed to initialize the frontend.",
        "user_hint": "Check your Jupyter environment or browser and retry.",
        "dev_message": "Viewer init failed (reason: {reason}).",
        "dev_hint": "Inspect frontend logs and widget payload.",
        "qa_message": "Viewer init failed (reason: {reason}).",
        "qa_hint": "Capture frontend logs and repro steps.",
        "agent_message": "Viewer init failed (reason: {reason}).",
        "agent_hint": "Collect logs and validate frontend bundle.",
    },
    "MOLSYSVIEWER-PAYLOAD-INVALID-COORDINATES": {
        "title": "Invalid coordinates payload",
        "user_message": "The MolSys payload has invalid coordinates.",
        "user_hint": "Check the coordinates array and try again.",
        "dev_message": "Invalid coordinates payload: {detail}.",
        "dev_hint": "Validate payload schema before conversion.",
        "qa_message": "Invalid coordinates payload: {detail}.",
        "qa_hint": "Add coverage for invalid coordinates payloads.",
        "agent_message": "Invalid coordinates payload: {detail}.",
        "agent_hint": "Validate payload schema in ingestion.",
    },
    "MOLSYSVIEWER-PAYLOAD-INVALID-BOX-VECTORS": {
        "title": "Invalid box vectors",
        "user_message": "The MolSys payload has invalid box vectors.",
        "user_hint": "Check the box vectors and try again.",
        "dev_message": "Invalid box vectors: {detail}.",
        "dev_hint": "Validate payload schema before conversion.",
        "qa_message": "Invalid box vectors: {detail}.",
        "qa_hint": "Add coverage for invalid box payloads.",
        "agent_message": "Invalid box vectors: {detail}.",
        "agent_hint": "Validate payload schema in ingestion.",
    },
    "MOLSYSVIEWER-PAYLOAD-INVALID-BOND-PAIRS": {
        "title": "Invalid bond pairs",
        "user_message": "The MolSys payload has invalid bond pairs.",
        "user_hint": "Check bond pair indices and try again.",
        "dev_message": "Invalid bond pairs: {detail}.",
        "dev_hint": "Validate bond pairs before conversion.",
        "qa_message": "Invalid bond pairs: {detail}.",
        "qa_hint": "Add coverage for invalid bond pairs.",
        "agent_message": "Invalid bond pairs: {detail}.",
        "agent_hint": "Validate bond pairs in ingestion.",
    },
    "MOLSYSVIEWER-PAYLOAD-INVALID-BOND-INDICES": {
        "title": "Invalid bond indices",
        "user_message": "The MolSys payload has invalid bond indices.",
        "user_hint": "Check bond indices and try again.",
        "dev_message": "Invalid bond indices: {detail}.",
        "dev_hint": "Validate bond indices before conversion.",
        "qa_message": "Invalid bond indices: {detail}.",
        "qa_hint": "Add coverage for invalid bond indices.",
        "agent_message": "Invalid bond indices: {detail}.",
        "agent_hint": "Validate bond indices in ingestion.",
    },
}

SIGNALS = {
    "molsysviewer.argument_error": {"extra_required": ["argument", "caller"]},
    "molsysviewer.file_already_handled": {"extra_required": ["filename"]},
    "molsysviewer.iterator_error": {"extra_required": ["caller"]},
    "molsysviewer.library_not_found": {"extra_required": ["library", "caller"]},
    "molsysviewer.molecular_system_needed": {"extra_required": ["caller"]},
    "molsysviewer.molecular_systems_needed": {"extra_required": ["caller"]},
    "molsysviewer.not_compatible_conversion": {
        "extra_required": ["from_form", "to_form", "missing_arguments", "caller"]
    },
    "molsysviewer.not_implemented_conversion": {
        "extra_required": ["from_form", "to_form", "caller"]
    },
    "molsysviewer.not_implemented_iterator": {"extra_required": ["form", "caller"]},
    "molsysviewer.not_implemented_method": {"extra_required": ["caller"]},
    "molsysviewer.not_supported_form": {"extra_required": ["form", "caller"]},
    "molsysviewer.not_supported_syntax": {"extra_required": ["syntax", "caller"]},
    "molsysviewer.not_with_this_form": {"extra_required": ["caller"]},
    "molsysviewer.not_digested_argument": {"extra_required": ["argument", "caller"]},
    "molsysviewer.viewer_init_failed": {"extra_required": ["reason", "message"]},
    "molsysviewer.payload_invalid_coordinates": {"extra_required": ["detail"]},
    "molsysviewer.payload_invalid_box_vectors": {"extra_required": ["detail"]},
    "molsysviewer.payload_invalid_bond_pairs": {"extra_required": ["detail"]},
    "molsysviewer.payload_invalid_bond_indices": {"extra_required": ["detail"]},
}
