import path from "node:path";
import { fileURLToPath } from "node:url";
import { mkdir, copyFile } from "node:fs/promises";
import { build } from "esbuild";

const __filename = fileURLToPath(import.meta.url);
const root = path.resolve(path.dirname(__filename), "..");
const outDir = path.join(root, "dist");
const outfile = path.join(outDir, "viewer.js");
const banner =
  "// @generated\n// This file is generated from js/src/index.ts and related TS sources.\n// DO NOT EDIT THIS FILE BY HAND.\n";

await mkdir(outDir, { recursive: true });

await build({
  entryPoints: [path.join(root, "src", "index.ts")],
  bundle: true,
  format: "esm",
  sourcemap: true,
  outfile,
  tsconfig: path.join(root, "tsconfig.json"),
  banner: { js: banner },
});

await copyFile(outfile, path.join(root, "..", "viewer.js"));
await copyFile(`${outfile}.map`, path.join(root, "..", "viewer.js.map"));
