import path from "node:path";
import { fileURLToPath } from "node:url";
import { mkdir, copyFile, readFile } from "node:fs/promises";
import { build } from "esbuild";

const __filename = fileURLToPath(import.meta.url);
const root = path.resolve(path.dirname(__filename), "..");
const outDir = path.join(root, "dist");
const outfile = path.join(outDir, "viewer.js");
const banner =
  "// @generated\n// This file is generated from js/src/index.ts and related TS sources.\n// DO NOT EDIT THIS FILE BY HAND.\n";

// The runtime has to know which MolSysViewer built it, so an exported page can
// be told when the scene it carries was produced by a different one. Read from
// the same file `sync-python-version.mjs` reads, so there is one source.
const versionFile = path.join(root, "..", "_version.py");
const versionMatch = (await readFile(versionFile, "utf8")).match(
  /__version__\s*=\s*["']([^"']+)["']/,
);
if (!versionMatch) {
  throw new Error(`Unable to find __version__ in ${versionFile}`);
}
const runtimeVersion = versionMatch[1];

await mkdir(outDir, { recursive: true });

await build({
  entryPoints: [path.join(root, "src", "index.ts")],
  bundle: true,
  format: "esm",
  sourcemap: true,
  outfile,
  tsconfig: path.join(root, "tsconfig.json"),
  banner: { js: banner },
  define: { __MOLSYSVIEWER_VERSION__: JSON.stringify(runtimeVersion) },
});

await copyFile(outfile, path.join(root, "..", "viewer.js"));
await copyFile(`${outfile}.map`, path.join(root, "..", "viewer.js.map"));
