import path from "node:path";
import { fileURLToPath } from "node:url";
import { mkdir, copyFile, readFile } from "node:fs/promises";
import { build } from "esbuild";
import { resolveBuildVersion } from "./resolve-version.mjs";

const __filename = fileURLToPath(import.meta.url);
const root = path.resolve(path.dirname(__filename), "..");
const outDir = path.join(root, "dist");
const outfile = path.join(outDir, "viewer.js");
const banner =
  "// @generated\n// This file is generated from js/src/index.ts and related TS sources.\n// DO NOT EDIT THIS FILE BY HAND.\n";

// The runtime has to know which MolSysViewer built it, so an exported page can
// be told when the scene it carries was produced by a different one. Resolved by
// `resolve-version.mjs`, the same way `sync-python-version.mjs` resolves it, so there is
// one source and one fallback order.
const packageJson = JSON.parse(
  await readFile(path.join(root, "package.json"), "utf8"),
);
const { version: runtimeVersion } = resolveBuildVersion({
  versionFile: path.join(root, "..", "_version.py"),
  fallbackVersion: packageJson.version || packageJson.pythonVersion,
});

await mkdir(outDir, { recursive: true });

await build({
  entryPoints: [path.join(root, "src", "index.ts")],
  bundle: true,
  format: "esm",
  sourcemap: true,
  outfile,
  tsconfig: path.join(root, "tsconfig.json"),
  banner: { js: banner },
  define: { __MOLSYSVIEWER_VERSION__: JSON.stringify(runtimeVersion) },
});

await copyFile(outfile, path.join(root, "..", "viewer.js"));
await copyFile(`${outfile}.map`, path.join(root, "..", "viewer.js.map"));
