/**
 * What does a panel-only endpoint actually render once it has its snapshot?
 *
 * Reported by hand on 2026-08-01: the popped-out Studio/Add-ons window shows its
 * two header buttons and nothing else — no left menu, no subpanels. The welcome
 * card that used to cover them is gone, so this is a second, separate problem
 * underneath it.
 *
 * Feeds a real panel snapshot (generated by `build_popup_scene_snapshot("panel")`
 * on a populated viewer) into a panel-only controller and reports what is in the
 * DOM, so the difference between "the summaries never arrived" and "they arrived
 * and nothing is visible" is observable rather than guessed at.
 */
import process from "node:process";
import { chromium } from "./e2e-browser";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { readFileSync } from "node:fs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

async function run() {
    const envBin = process.env.PW_CHROMIUM_BIN || "/usr/bin/google-chrome";
    const browser = await chromium.launch({ headless: true, executablePath: envBin } as any);
    const page = await browser.newPage();
    const errors: string[] = [];
    page.on("pageerror", err => errors.push(String(err)));
    page.on("console", m => { if (m.type() === "error") errors.push(`console: ${m.text()}`); });

    await page.goto("about:blank");
    await page.setContent(
        `<!doctype html><html><body><div id="panel" style="width:460px;height:700px;"></div></body></html>`,
    );
    await page.addScriptTag({ path: resolve(__dirname, "harness.bundle.js") });
    await page.waitForFunction(() => typeof (window as any).Harness !== "undefined");

    const snapshot = JSON.parse(readFileSync(process.env.PROBE_SNAPSHOT!, "utf8"));
    // Derive the hierarchy the way a host does, in a throwaway viewer, then hand
    // it to the panel-only controller exactly as the relay would.
    await page.evaluate(async (pdb: string) => {
        const host = document.createElement("div");
        host.style.cssText = "width:800px;height:600px";
        host.id = "tmphost";
        document.body.appendChild(host);
        const c = await (window as any).Harness.createController("tmphost");
        await c.handleMessage({ op: "load_structure_from_string", data: pdb, format: "pdb", label: "h" });
        for (let i = 0; i < 80; i++) {
            const s = (c as any).plugin.managers.structure.hierarchy.current.structures[0]?.cell.obj?.data;
            if (s && s.elementCount > 0) break;
            await new Promise(r => setTimeout(r, 100));
        }
        (window as any).__hierarchy = JSON.parse(JSON.stringify(c.getHierarchyItems()));
        host.remove();
    }, readFileSync(process.env.PROBE_PDB!, "utf8"));

    const report = await page.evaluate(async (messages: any[]) => {
        const controller = await (window as any).Harness.createController("panel", {
            isPanelOnly: true,
            panelModeStyle: "split",
        });
        // The host relays the hierarchy it derived; without it System has nothing,
        // because the panel snapshot carries no geometry by design.
        if ((window as any).__hierarchy) {
            (controller as any).setHierarchyItems((window as any).__hierarchy);
        }
        for (const msg of messages) {
            await controller.handleMessage(msg);
        }
        await new Promise(r => setTimeout(r, 600));

        const root = document.getElementById("panel")!;
        const visible = (el: Element | null) => {
            if (!el) return false;
            const style = getComputedStyle(el as HTMLElement);
            const rect = (el as HTMLElement).getBoundingClientRect();
            return style.display !== "none" && style.visibility !== "hidden"
                && rect.width > 0 && rect.height > 0;
        };
        /** Text the user can actually see. `textContent` includes hidden nodes, so
         *  it proves nothing about what reached the screen. */
        const visibleText = () => {
            let out = "";
            const walk = (el: Element) => {
                if (!visible(el)) return;
                for (const node of Array.from(el.childNodes)) {
                    if (node.nodeType === Node.TEXT_NODE) out += " " + (node.textContent ?? "");
                    else if (node.nodeType === Node.ELEMENT_NODE) walk(node as Element);
                }
            };
            walk(root);
            return out;
        };
        const countText = (needle: string) => visibleText().includes(needle);

        // Which panel roots exist, and which of them are actually on screen.
        const named = (selector: string) => {
            const el = root.querySelector(selector);
            return { present: !!el, visible: visible(el) };
        };

        return {
            addonsPanelVisible: (controller as any).addonsPanel?.isVisible?.()
                ?? (controller as any).addonsPanel?.visible ?? null,
            groupPanelVisible: (controller as any).groupPanel?.isVisible?.() ?? null,
            groupPanelExpanded: (controller as any).groupPanel?.expanded ?? null,
            // Evidence the summaries were received and stored, independent of DOM.
            regionSummaries: ((controller as any).state?.getRegionSummaries?.() ?? []).length,
            // Evidence they reached the screen.
            mentionsRegionTag: countText("helice"),
            mentionsMeasurementTag: countText("larga"),
            mentionsAnnotationTag: countText("nota"),
            textLength: (root.textContent ?? "").trim().length,
            addonsRoot: named('[data-molsysviewer-addons-panel]'),
            groupRoot: named('[data-molsysviewer-group-panel]'),
            visibleTextLength: visibleText().trim().length,
            // The subpanels render one tab at a time, so the summaries only reach
            // the screen on the tab that owns them. Switching is the real test that
            // content is built from the snapshot rather than from a structure.
            tabs: await (async () => {
                const gp: any = (controller as any).groupPanel;
                const out: Record<string, boolean> = {};
                for (const [tab, needle] of [
                    ["regions", "helice"], ["measures", "measurement visible"],
                    ["annotations", "extremo"], ["system", "chain"],
                ] as Array<[string, string]>) {
                    gp?.switchTab?.(tab);
                    await new Promise(r => setTimeout(r, 250));
                    // Needles are what the row actually shows. The Measures row
                    // renders the value and endpoints, not the tag — an earlier
                    // version looked for the tag and reported a defect that was
                    // only a badly chosen string.
                    out[tab] = visibleText().includes(needle);
                    if (tab === "system") (out as any).systemText = visibleText().replace(/\s+/g, " ").trim().slice(0, 420);
                }
                return out;
            })(),
        };
    }, snapshot);

    console.log(JSON.stringify(report, null, 1));
    if (errors.length) console.log("ERRORS:", errors.slice(0, 8));
    await browser.close();
}

run().catch(err => { console.error(err); process.exit(1); });
