package:
  name: molsysviewer
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"

source:
  path: ../../   # raíz del repositorio (ajusta si tu estructura es otra)

build:
  number: 1

requirements:
  host:
    - python
    - pip
    - nodejs  # para npm y el build de viewer.js
  run:
    - python
    - anywidget

about:
  home: "https://github.com/uibcdf/molsysviewer"
  license: "MIT"  # o lo que toque
  summary: "Molecular viewer based on Mol* and anywidget."
