name: Ruff Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'molsysviewer/**/*.py'
      - 'pyproject.toml'
      - '.github/workflows/ruff.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'molsysviewer/**/*.py'
      - 'pyproject.toml'
      - '.github/workflows/ruff.yaml'
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff Check
        run: ruff check molsysviewer --select F821,F822,F823,F841,B006,B023
